[package]
name = "microbit-led-matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.0"
microbit-v2 = "0.13.0"
panic-halt = "0.2.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }